name: docker build/push

on: push

env:
    dockerfile: Dockerfile
    image_name: ${{ github.repository }}

jobs:
  docker-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -f ${{ env.dockerfile }} --tag ghcr.io/${{ env.image_name }}:latest .

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ env.image_name }}:latest
