name: SNAPSHOT build/deploy

on:
  pull_request:
    branches:
      - dev
    types:
      - closed   # triggers when a PR targeting dev is closed

env:
    dockerfile: Dockerfile
    image_name: ${{ github.repository }}

jobs:
  build-docker:
    if: github.event.pull_request.merged == true
    uses: locuta/workflows-templates/.github/workflows/build-docker-snapshot.yml@feat/flux-sync-ci
    with:
      dockerfile: Dockerfile
  
  deploy:
    needs: 
      - build-docker
    uses: locuta/workflows-templates/.github/workflows/deploy-gitops-dev.yml@feat/flux-sync-ci
    with:
      gitops_path: apps/base/arnaud
    secrets:
      CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}